[package]
name = "snowflake-connector"
version = "0.1.0"
edition = "2021"

[dependencies]
reqwest = { version = "0.11", features = ["json", "gzip"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
thiserror = "1.0"
uuid = { version = "1.3", features = ["v4"] }

[dev-dependencies]
tokio = { version = "1.32", features = ["macros", "rt"] }
rstest = "0.18"
